home: "https://jwannamaker.github.io"
baseurl: "/LearnOpenGL"
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
collections:
  pages:
    output: true
    sort_by: order